name: yowshare
publish_to: 'none'


environment:
  sdk: ">=3.4.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  file_picker: ^8.0.3
  permission_handler: ^11.3.1
# flutter_rust_bridge: add in STEP 4 when we wire FFI


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0