[package]
name = "yowshare_core"
version = "0.1.0"
edition = "2021"


[lib]
name = "yowshare_core"
path = "src/lib.rs"


[[bin]]
name = "yowshare_core_cli"
path = "src/bin/cli.rs"


[dependencies]
quinn = "0.10"
tokio = { version = "1.40", features = ["full"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
rcgen = "0.12"
rustls = "0.21"
bytes = "1"
sha2 = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"